### ISSUE TITLE
Add logo in the url address of the site

### ISSUE THREAD

**Issue by haythamodeh** [aelbarbary/tamkeen#15]

**Comment by aelbarbary** [comment]
@haythamodeh , I thought you fixed this already ?

**Comment by haythamodeh** [comment]
i didnt, tried putting it, but it didnt work, something seems to be wrong.

**Comment by aelbarbary** [comment]
I can see it already in chrome !!

![image](https://cloud.githubusercontent.com/assets/5176721/22908167/c4377c6a-f201-11e6-871a-93467ec7c1e7.png)

**Comment by aelbarbary** [comment]
Closing this issue
