### ISSUE TITLE
hide events sections if there is no upcoming events

### ISSUE THREAD

**Issue by aelbarbary** [aelbarbary/tamkeen#2]
![image](https://cloud.githubusercontent.com/assets/5176721/22716799/577131ca-ed4c-11e6-829c-6ea6205c2ce4.png)

we need to hide this sections all together if there is any scheduled events in the future

**Comment by haythamodeh** [comment]
i dont exactly understand why, i think its normal to have that, maybe instead of no coming events we can say events coming soon

**Comment by aelbarbary** [comment]
I like your idea. Let's change the message to "our next event is coming soon"

**Comment by aelbarbary** [comment]
Closing this issue after @haythamodeh fix
