### ISSUE TITLE
Add tamkeen logo in the Title bar

### ISSUE THREAD

**Issue by aelbarbary** [aelbarbary/tamkeen#8]
![image](https://cloud.githubusercontent.com/assets/5176721/22847045/82924146-ef9f-11e6-9488-3fcb359438be.png)

**Comment by aelbarbary** [comment]
@haythamodeh  let me know if you can take this ?

**Comment by haythamodeh** [comment]
ok np, i can try to do it, should be no problem.

**Comment by aelbarbary** [comment]
fixed by @haythamodeh
